export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const GET_GIT_HISTORY_REQUEST = 'GET_GIT_HISTORY_REQUEST';
export const GET_GIT_HISTORY_SUCCEESS = 'GET_GIT_HISTORY_SUCCEESS';
export const GET_GIT_HISTORY_ERROR = 'GET_GIT_HISTORY_ERROR';
