export const data = [
    {
        status: 'success',
        buildNum: '#1368',
        title: 'add documentation for postgres scaler',
        branch: 'master',
        hash: '9c9f0b9',
        author: 'Philip Kirkorov',
        date: '21 янв, 03:06',
        duration: '1 ч 20 мин',
    },
    {
        status: 'error',
        buildNum: '#1367',
        title: 'Super cool UI kit for making websites that look like games of old',
        branch: 'super-cool-ui-kit',
        hash: '952e5567',
        author: 'Vadim Makeev',
        date: '21 янв, 03:06',
        duration: '1 ч 20 мин',
    },
    {
        status: 'success',
        buildNum: '#1366',
        title: 'Merge branch "master" of github.com:jaywcjlove/awesome ui kit',
        branch: 'master',
        hash: 'b4636ab',
        author: 'Philip Kirkorov',
        date: '21 янв, 03:06',
        duration: '1 ч 20 мин',
    },
    {
        status: 'load',
        buildNum: '#1365',
        title: 'upgrade typescript to 3.8',
        branch: 'master',
        hash: 'b4636ab',
        author: 'Philip Kirkorov',
        date: '21 янв, 03:06',
        duration: '1 ч 20 мин',
    },
    {
        status: 'success',
        buildNum: '#1364',
        title: 'add documentation for postgres scaler',
        branch: 'master',
        hash: 'b4636ab',
        author: 'Philip Kirkorov',
        date: '21 янв, 03:06',
        duration: '1 ч 20 мин',
    },
    {
        status: 'error',
        buildNum: '#1363',
        title: 'replace all `div` to `article`',
        branch: 'master',
        hash: '952e5567',
        author: 'Vadim Makeev',
        date: '21 янв, 03:06',
        duration: '1 ч 20 мин',
    },
    {
        status: 'success',
        buildNum: '#1362',
        title: 'improved accessibility',
        branch: 'master',
        hash: 'e41e4cc',
        author: 'Philip Kirkorov',
        date: '21 янв, 03:06',
        duration: '1 ч 20 мин',
    },
    {
        status: 'success',
        buildNum: '#1350',
        title: 'fix: upload 别片类型',
        branch: 'master',
        hash: 'e41e4cc',
        author: 'Philip Kirkorov',
        date: '21 янв, 03:06',
        duration: '1 ч 50 мин',
    },
    {
        status: 'success',
        buildNum: '#1349',
        title: 'Form item has default height align with form size',
        branch: 'master',
        hash: 'e41e4cc',
        author: 'Philip Kirkorov',
        date: '21 янв, 12:06',
        duration: '1 ч 20 мин',
    },
];
